# Generated by Django 4.2.7 on 2026-02-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AcademicYear',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('start_date', models.DateField()),
                        ('end_date', models.DateField()),
                        ('is_active', models.BooleanField(default=True)),
                        ('is_current', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'school_academicyear',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='GradeLevel',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50, unique=True)),
                        ('order', models.PositiveIntegerField(default=1)),
                        ('description', models.TextField(blank=True)),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'school_gradelevel',
                        'ordering': ['order', 'name'],
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='SchoolClass',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('stream', models.CharField(blank=True, max_length=50)),
                        ('section_name', models.CharField(blank=True, max_length=50)),
                        ('room', models.CharField(blank=True, max_length=100)),
                        ('capacity', models.PositiveIntegerField(default=40)),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'school_schoolclass',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='Term',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('start_date', models.DateField()),
                        ('end_date', models.DateField()),
                        ('billing_date', models.DateField(blank=True, null=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('is_current', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'school_term',
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
