# Generated by Django 4.2.7 on 2026-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualsession',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
