# Generated by Django 4.2.7 on 2026-03-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text="e.g. '2025' or '2025-Q1'", max_length=20)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_book_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('asset', 'period_label')},
            },
        ),
    ]
