# Generated by Django 4.2.7 on 2026-03-09 08:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_performancegoal_performancereview_trainingprogram_and_more'),
        ('school', '0031_store_dispensary'),
        ('assets', '0002_depreciation_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetdepreciation',
            options={},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_by_name',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_to_name',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assetmaintenancerecord',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='assetmaintenancerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assetmaintenancerecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assetmaintenancerecord',
            name='technician_name',
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_to_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='return_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='performed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Returned', 'Returned'), ('Lost', 'Lost'), ('Damaged', 'Damaged')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='depreciation_method',
            field=models.CharField(choices=[('none', 'None (No Depreciation)'), ('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance (200% / Double Declining)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, help_text='Used for depreciation calculations', null=True),
        ),
        migrations.AlterField(
            model_name='assetdepreciation',
            name='accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='assetdepreciation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetdepreciation',
            name='depreciation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='assetdepreciation',
            name='net_book_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='assetdepreciation',
            name='period_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assetmaintenancerecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='assetmaintenancerecord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetmaintenancerecord',
            name='maintenance_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmaintenancerecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
