# Generated by Django 4.2.7 on 2026-03-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetdepreciation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('warranty_number', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('coverage_details', models.TextField(blank=True)),
                ('contact_info', models.CharField(blank=True, max_length=300)),
                ('alert_days_before', models.PositiveIntegerField(default=30, help_text='Days before expiry to alert')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('void', 'Void')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('transferred_by', models.CharField(blank=True, max_length=200)),
                ('transfer_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_type', models.CharField(choices=[('sold', 'Sold'), ('donated', 'Donated'), ('scrapped', 'Scrapped / Written Off'), ('stolen', 'Stolen / Lost'), ('transferred_out', 'Transferred Out')], max_length=20)),
                ('disposal_date', models.DateField()),
                ('disposed_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disposal_reason', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='assets.asset')),
            ],
        ),
    ]
