from django.urls import path

from .views import (
    ParentAcademicsAnalysisView,
    ParentAcademicsAssessmentsView,
    ParentAcademicsGradesView,
    ParentAnnouncementsView,
    ParentAssignmentSubmitView,
    ParentAssignmentsView,
    ParentAttendanceCalendarView,
    ParentAttendanceSummaryView,
    ParentBehaviorAcknowledgeView,
    ParentBehaviorIncidentsView,
    ParentCalendarView,
    ParentChangePasswordView,
    ParentDashboardActivityView,
    ParentDashboardAlertsView,
    ParentDashboardKpiView,
    ParentDashboardUpcomingView,
    ParentDashboardView,
    ParentEventRsvpView,
    ParentEventsView,
    ParentFinanceInvoiceDownloadView,
    ParentFinanceInvoicesView,
    ParentFinancePayView,
    ParentFinancePaymentsView,
    ParentFinanceReceiptView,
    ParentFinanceStatementView,
    ParentFinanceSummaryView,
    ParentLeaveRequestView,
    ParentLibraryBorrowingsView,
    ParentLibraryHistoryView,
    ParentLinkAdminDetailView,
    ParentLinkAdminListCreateView,
    ParentMessagesView,
    ParentNotificationPreferencesView,
    ParentNotificationReadView,
    ParentNotificationsView,
    ParentProfileView,
    ParentReportCardDownloadView,
    ParentReportCardsView,
    ParentTimetableExportView,
    ParentTimetableView,
    ParentHealthView,
    ParentTransportView,
)

urlpatterns = [
    path("dashboard/", ParentDashboardView.as_view()),
    path("dashboard/kpis/", ParentDashboardKpiView.as_view()),
    path("dashboard/alerts/", ParentDashboardAlertsView.as_view()),
    path("dashboard/activity/", ParentDashboardActivityView.as_view()),
    path("dashboard/upcoming/", ParentDashboardUpcomingView.as_view()),
    path("academics/grades/", ParentAcademicsGradesView.as_view()),
    path("academics/report-cards/", ParentReportCardsView.as_view()),
    path("academics/report-cards/<int:card_id>/download/", ParentReportCardDownloadView.as_view()),
    path("academics/analysis/", ParentAcademicsAnalysisView.as_view()),
    path("academics/assessments/", ParentAcademicsAssessmentsView.as_view()),
    path("attendance/calendar/", ParentAttendanceCalendarView.as_view()),
    path("attendance/summary/", ParentAttendanceSummaryView.as_view()),
    path("attendance/leave-request/", ParentLeaveRequestView.as_view()),
    path("behavior/incidents/", ParentBehaviorIncidentsView.as_view()),
    path("behavior/<int:incident_id>/acknowledge/", ParentBehaviorAcknowledgeView.as_view()),
    path("finance/summary/", ParentFinanceSummaryView.as_view()),
    path("finance/invoices/", ParentFinanceInvoicesView.as_view()),
    path("finance/invoices/<int:invoice_id>/download/", ParentFinanceInvoiceDownloadView.as_view()),
    path("finance/payments/", ParentFinancePaymentsView.as_view()),
    path("finance/payments/<int:payment_id>/receipt/", ParentFinanceReceiptView.as_view()),
    path("finance/pay/", ParentFinancePayView.as_view()),
    path("finance/statement/", ParentFinanceStatementView.as_view()),
    path("messages/", ParentMessagesView.as_view()),
    path("announcements/", ParentAnnouncementsView.as_view()),
    path("notifications/", ParentNotificationsView.as_view()),
    path("notifications/<int:notification_id>/read/", ParentNotificationReadView.as_view()),
    path("notification-preferences/", ParentNotificationPreferencesView.as_view()),
    path("timetable/", ParentTimetableView.as_view()),
    path("timetable/export/", ParentTimetableExportView.as_view()),
    path("calendar/", ParentCalendarView.as_view()),
    path("assignments/", ParentAssignmentsView.as_view()),
    path("assignments/<int:assignment_id>/submit/", ParentAssignmentSubmitView.as_view()),
    path("events/", ParentEventsView.as_view()),
    path("events/<int:event_id>/rsvp/", ParentEventRsvpView.as_view()),
    path("library/borrowings/", ParentLibraryBorrowingsView.as_view()),
    path("library/history/", ParentLibraryHistoryView.as_view()),
    path("admin/links/", ParentLinkAdminListCreateView.as_view()),
    path("admin/links/<int:link_id>/", ParentLinkAdminDetailView.as_view()),
    path("profile/", ParentProfileView.as_view()),
    path("profile/change-password/", ParentChangePasswordView.as_view()),
    path("health/", ParentHealthView.as_view()),
    path("transport/", ParentTransportView.as_view()),
]
