# Generated by Django 4.2.7 on 2026-03-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_globalsuperadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_students', models.PositiveIntegerField(default=200)),
                ('max_storage_gb', models.PositiveIntegerField(default=5)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_storage_gb',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_students',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='clients.subscriptionplan'),
        ),
    ]
