# Generated by Django 4.2.7 on 2026-03-03 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0009_backupjob_securityincident_restorejob_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformNotificationDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE_SCHEDULED", "Maintenance Scheduled"),
                            ("MAINTENANCE_STARTED", "Maintenance Started"),
                            ("MAINTENANCE_COMPLETED", "Maintenance Completed"),
                            ("MAINTENANCE_CANCELLED", "Maintenance Cancelled"),
                            ("DEPLOYMENT_STARTED", "Deployment Started"),
                            ("DEPLOYMENT_COMPLETED", "Deployment Completed"),
                            ("DEPLOYMENT_FAILED", "Deployment Failed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("channel", models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("IN_APP", "In-App")], max_length=20)),
                ("status", models.CharField(choices=[("QUEUED", "Queued"), ("SENT", "Sent"), ("FAILED", "Failed")], default="QUEUED", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_notification_dispatches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maintenance_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_dispatches",
                        to="clients.maintenancewindow",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_dispatches",
                        to="clients.deploymentrelease",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_dispatches",
                        to="clients.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event_type"], name="clients_pla_event_t_8a08d2_idx"),
                    models.Index(fields=["channel"], name="clients_pla_channel_8ff66a_idx"),
                    models.Index(fields=["status"], name="clients_pla_status_2a9af5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeploymentHookRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hook_type", models.CharField(choices=[("TRIGGER", "Trigger"), ("ROLLBACK", "Rollback")], max_length=20)),
                ("status", models.CharField(choices=[("SUCCESS", "Success"), ("FAILED", "Failed")], default="FAILED", max_length=20)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployment_hook_runs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hook_runs", to="clients.deploymentrelease")),
            ],
            options={
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(fields=["hook_type"], name="clients_dep_hook_ty_48df16_idx"),
                    models.Index(fields=["status"], name="clients_dep_status_59ac5e_idx"),
                    models.Index(fields=["executed_at"], name="clients_dep_execute_a65618_idx"),
                ],
            },
        ),
    ]
