# Generated by Django 4.2.7 on 2026-03-03 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0010_deploymenthookrun_platformnotificationdispatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupExecutionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("engine_mode", models.CharField(default="mock", max_length=50)),
                ("command", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("SUCCESS", "Success"), ("FAILED", "Failed")], default="FAILED", max_length=20)),
                ("output_path", models.CharField(blank=True, max_length=255)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("logs", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "backup",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="execution_runs", to="clients.backupjob"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_execution_runs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["status"], name="clients_bac_status_048f86_idx"),
                    models.Index(fields=["engine_mode"], name="clients_bac_engine__dcf23c_idx"),
                    models.Index(fields=["started_at"], name="clients_bac_started_580cd7_idx"),
                ],
            },
        ),
    ]
