# Generated by Django 4.2.7 on 2026-03-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_platformsetting_globalsuperadmin_role_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backupexecutionrun',
            new_name='clients_bac_status_9e38ad_idx',
            old_name='clients_bac_status_048f86_idx',
        ),
        migrations.RenameIndex(
            model_name='backupexecutionrun',
            new_name='clients_bac_engine__902ea3_idx',
            old_name='clients_bac_engine__dcf23c_idx',
        ),
        migrations.RenameIndex(
            model_name='backupexecutionrun',
            new_name='clients_bac_started_975d4d_idx',
            old_name='clients_bac_started_580cd7_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymenthookrun',
            new_name='clients_dep_hook_ty_c66524_idx',
            old_name='clients_dep_hook_ty_48df16_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymenthookrun',
            new_name='clients_dep_status_ddf180_idx',
            old_name='clients_dep_status_59ac5e_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymenthookrun',
            new_name='clients_dep_execute_a832f6_idx',
            old_name='clients_dep_execute_a65618_idx',
        ),
        migrations.RenameIndex(
            model_name='platformnotificationdispatch',
            new_name='clients_pla_event_t_368566_idx',
            old_name='clients_pla_event_t_8a08d2_idx',
        ),
        migrations.RenameIndex(
            model_name='platformnotificationdispatch',
            new_name='clients_pla_channel_29571a_idx',
            old_name='clients_pla_channel_8ff66a_idx',
        ),
        migrations.RenameIndex(
            model_name='platformnotificationdispatch',
            new_name='clients_pla_status_f9d715_idx',
            old_name='clients_pla_status_2a9af5_idx',
        ),
    ]
