# Generated by Django 4.2.7 on 2026-03-27 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_rename_clients_bac_status_048f86_idx_clients_bac_status_9e38ad_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_domain', models.CharField(max_length=255)),
                ('verification_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending DNS verification'), ('VERIFIED', 'DNS verified — awaiting activation'), ('ACTIVE', 'Active'), ('FAILED', 'Verification failed'), ('REJECTED', 'Rejected by platform')], default='PENDING', max_length=20)),
                ('verification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_verification_attempt', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_by_username', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain_requests', to='clients.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
