# Generated by Django 4.2.7 on 2026-02-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('action', models.CharField(max_length=50)),
                        ('model_name', models.CharField(max_length=100)),
                        ('object_id', models.CharField(max_length=50)),
                        ('user_id', models.IntegerField(null=True)),
                        ('details', models.TextField(blank=True)),
                    ],
                    options={
                        'db_table': 'school_auditlog',
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
