# Generated by Django 4.2.7 on 2026-02-12 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('audience_type', models.CharField(choices=[('All', 'All'), ('Students', 'Students'), ('Parents', 'Parents'), ('Staff', 'Staff'), ('Class', 'Class'), ('Department', 'Department'), ('Custom', 'Custom')], default='All', max_length=20)),
                ('audience_filter', models.JSONField(blank=True, default=dict)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('Text', 'Text'), ('File', 'File'), ('Image', 'Image'), ('System', 'System')], default='Text', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Sent', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('Direct', 'Direct'), ('Group', 'Group'), ('Broadcast', 'Broadcast'), ('Class', 'Class'), ('Department', 'Department')], default='Direct', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Sending', 'Sending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], default='SMS', max_length=20)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('System', 'System'), ('Financial', 'Financial'), ('Academic', 'Academic'), ('Behavioral', 'Behavioral'), ('HR', 'HR'), ('Event', 'Event'), ('Emergency', 'Emergency')], default='System', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Informational', 'Informational')], default='Informational', max_length=20)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Sent', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Financial', 'Financial'), ('Event', 'Event'), ('Alert', 'Alert'), ('System', 'System')], default='System', max_length=20)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('InApp', 'InApp'), ('Push', 'Push'), ('WhatsApp', 'WhatsApp')], default='Email', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='communication/messages/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.communicationmessage')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Opened', 'Opened'), ('Clicked', 'Clicked'), ('Bounced', 'Bounced'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('bounce_reason', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communication.emailcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.conversation'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communication.communicationmessage'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('System', 'System'), ('Financial', 'Financial'), ('Academic', 'Academic'), ('Behavioral', 'Behavioral'), ('HR', 'HR'), ('Event', 'Event'), ('Emergency', 'Emergency')], default='System', max_length=20)),
                ('channel_in_app', models.BooleanField(default=True)),
                ('channel_email', models.BooleanField(default=True)),
                ('channel_sms', models.BooleanField(default=False)),
                ('channel_push', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notification_type', 'id'],
                'unique_together': {('user', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='communication.communicationmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at', '-id'],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member'), ('Observer', 'Observer')], default='Member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communication.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at', '-id'],
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='communication.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at', '-id'],
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
