# Generated by Django 4.2.7 on 2026-02-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Message',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('recipient_type', models.CharField(max_length=20)),
                        ('recipient_id', models.IntegerField()),
                        ('subject', models.CharField(max_length=200)),
                        ('body', models.TextField()),
                        ('sent_at', models.DateTimeField(auto_now_add=True)),
                        ('status', models.CharField(max_length=20)),
                    ],
                    options={
                        'db_table': 'school_message',
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
