# Generated by Django 4.2.7 on 2026-03-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(blank=True, help_text='Name of student or alumni being mentored', max_length=200)),
                ('mentee_type', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], default='student', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('skills_offered', models.TextField(blank=True, help_text='Skills/areas mentor can help with')),
                ('areas_of_interest', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open / Seeking Mentee'), ('matched', 'Matched'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='open', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentor', to='alumni.alumniprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='General Fund', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money (M-Pesa)'), ('cheque', 'Cheque'), ('online', 'Online / Card')], default='mobile_money', max_length=20)),
                ('donation_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('received', 'Received'), ('acknowledged', 'Acknowledged'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='alumni.alumniprofile')),
            ],
        ),
    ]
