# Generated by Django 4.2.7 on 2026-02-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_module_alter_role_name_usermoduleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Submitted', 'Submitted'), ('Documents Received', 'Documents Received'), ('Interview Scheduled', 'Interview Scheduled'), ('Assessed', 'Assessed'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Enrolled', 'Enrolled'), ('Withdrawn', 'Withdrawn')], default='Submitted', max_length=30)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('assessment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('decision', models.CharField(choices=[('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applying_for_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolclass')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student')),
            ],
        ),
    ]
