# Generated by Django 4.2.7 on 2026-02-11 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0012_schoolprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='capacity',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='section_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='term',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gradelevel'),
        ),
    ]
