# Generated by Django 4.2.7 on 2026-03-08 09:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0029_tenantmodule_modulesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of each payment allocated to this vote head (0 = manual/unallocated)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_preloaded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('CASH', 'Cashbook'), ('BANK', 'Bankbook')], default='CASH', max_length=10)),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('RECEIPT', 'Receipt (Payment In)'), ('EXPENSE', 'Expense (Payment Out)'), ('ADJUSTMENT', 'Adjustment')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('amount_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_auto', models.BooleanField(default=False, help_text='Auto-created from payment/expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='school.expense')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='school.payment')),
            ],
            options={
                'ordering': ['book_type', 'entry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteHeadPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_head_allocations', to='school.payment')),
                ('vote_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='school.votehead')),
            ],
            options={
                'unique_together': {('payment', 'vote_head')},
            },
        ),
        migrations.CreateModel(
            name='BalanceCarryForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forwards_from', to='school.term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forwards', to='school.student')),
                ('to_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forwards_to', to='school.term')),
            ],
            options={
                'unique_together': {('student', 'from_term', 'to_term')},
            },
        ),
    ]
