# Generated by Django 4.2.7 on 2026-03-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_budget_add_name_remove_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('UNIFORM', 'Uniform'), ('TRIP', 'Trip'), ('BOOKS', 'Books'), ('ACTIVITY', 'Activity'), ('TRANSPORT', 'Transport'), ('MEALS', 'Meals'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.academicyear')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.term')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentOptionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_charges', to='school.invoice')),
                ('optional_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='school.optionalcharge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_charges', to='school.student')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('student', 'optional_charge')},
            },
        ),
    ]
