# Generated by Django 4.2.7 on 2026-03-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_optionalcharge_studentoptionalcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorderrequest',
            name='generated_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to='school.expense'),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
