# Generated by Django 4.2.7 on 2026-03-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_dispensary_delivery_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaryOutsideTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_type', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Other', 'Other')], default='Student', max_length=20)),
                ('referral_date', models.DateField()),
                ('facility_name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outside_treatments', to='school.student')),
            ],
            options={
                'ordering': ['-referral_date', '-created_at'],
            },
        ),
    ]
