# Generated by Django 4.2.7 on 2026-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_dispensary_outside_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='font_family',
            field=models.CharField(blank=True, default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='invoice_prefix',
            field=models.CharField(default='INV-', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='motto',
            field=models.CharField(blank=True, help_text='School motto / tagline', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='primary_color',
            field=models.CharField(default='#10b981', help_text='Hex color e.g. #10b981', max_length=16),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='secondary_color',
            field=models.CharField(default='#0ea5e9', max_length=16),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sms_provider',
            field=models.CharField(blank=True, help_text='e.g. africastalking, twilio', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sms_sender_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sms_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
