# Generated by Django 4.2.7 on 2026-03-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_add_branding_and_comm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmodulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=50)),
                ('submodule_key', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodule_permissions', to='school.role')),
            ],
            options={
                'unique_together': {('role', 'module_key', 'submodule_key')},
            },
        ),
    ]
