# Generated by Django 4.2.7 on 2026-03-13 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0038_add_submodule_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUT', 'Outgoing (Leaving this school)'), ('IN', 'Incoming (Joining from another school)')], default='OUT', max_length=3)),
                ('other_school', models.CharField(help_text='Name of the destination or source school', max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('clearance_completed', models.BooleanField(default=False, help_text='Clearance form signed')),
                ('academic_records_issued', models.BooleanField(default=False, help_text='Transcripts/report cards issued')),
                ('transfer_letter_issued', models.BooleanField(default=False, help_text='Official transfer letter issued')),
                ('fee_balance_cleared', models.BooleanField(default=False, help_text='All outstanding fees cleared')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='school.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
