# Generated by Django 4.2.7 on 2026-03-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_userprofile_admission_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('product_types', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('TENANT_SUPER_ADMIN', 'Tenant Super Admin'), ('ADMIN', 'School Administrator'), ('ACCOUNTANT', 'Finance Manager'), ('TEACHER', 'Teaching Staff'), ('PARENT', 'Parent / Guardian'), ('STUDENT', 'Student')], max_length=50, unique=True),
        ),
    ]
