# Generated by Django 4.2.7 on 2026-03-27 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0045_phase18_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossTenantTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('student', 'Student Transfer'), ('staff', 'Staff Transfer'), ('internal_student', 'Internal Student Transfer'), ('internal_staff', 'Internal Staff Transfer')], max_length=20)),
                ('entity_id', models.IntegerField(help_text='student_id or employee_id')),
                ('from_tenant_id', models.CharField(max_length=100)),
                ('to_tenant_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved_from', 'Approved by Source School'), ('approved_to', 'Approved by Destination School'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('fee_balance_cleared', models.BooleanField(default=False)),
                ('exam_in_progress', models.BooleanField(default=False, help_text='Flagged if active exam detected')),
                ('mid_term', models.BooleanField(default=False, help_text='Flagged if transfer is mid-term')),
                ('rejection_reason', models.TextField(blank=True)),
                ('from_class', models.CharField(blank=True, max_length=100)),
                ('to_class', models.CharField(blank=True, max_length=100)),
                ('from_stream', models.CharField(blank=True, max_length=100)),
                ('to_stream', models.CharField(blank=True, max_length=100)),
                ('from_department', models.CharField(blank=True, max_length=150)),
                ('to_department', models.CharField(blank=True, max_length=150)),
                ('from_role', models.CharField(blank=True, max_length=100)),
                ('to_role', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(help_text='hr.Employee pk')),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('tenant_id', models.CharField(max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_snapshot', models.JSONField(default=dict, help_text='Full entity data snapshot at time of transfer')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='attendance_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='attendance_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_student_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_due_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_student_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeitem',
            name='storeitem_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_created_at_idx',
        ),
        migrations.AddField(
            model_name='transferpackage',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='school.crosstenanttransfer'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_history', to='school.student'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.crosstenanttransfer'),
        ),
        migrations.AddField(
            model_name='staffhistory',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.crosstenanttransfer'),
        ),
        migrations.AddField(
            model_name='crosstenanttransfer',
            name='approved_from_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_from_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crosstenanttransfer',
            name='approved_to_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_to_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crosstenanttransfer',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crosstenanttransfer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
