# Generated by Django 4.2.7 on 2026-03-27 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0046_transfer_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='ADM-', help_text='e.g. STM- or 2025/', max_length=20)),
                ('year', models.PositiveIntegerField(default=2025, help_text='Current academic year used in number')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Last used sequence number')),
                ('padding', models.PositiveIntegerField(default=4, help_text='Zero-pad width e.g. 4 → 0001')),
                ('include_year', models.BooleanField(default=True, help_text='Include year in format: PREFIX-YEAR-SEQ')),
                ('reset_policy', models.CharField(choices=[('never', 'Never reset — numbers keep incrementing'), ('yearly', 'Reset sequence each academic year')], default='never', max_length=10)),
                ('transfer_policy', models.CharField(choices=[('new', 'Assign new admission number (store previous)'), ('keep', 'Retain old admission number from source school')], default='new', max_length=10)),
                ('auto_generate', models.BooleanField(default=True, help_text='Auto-generate on enrolment (vs. manual entry)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Settings',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('STUDENTS', 'Students'), ('STAFF', 'Staff'), ('FINANCE', 'Finance'), ('BRANDING', 'Branding'), ('COMMUNICATION', 'Communication'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'Document'), ('spreadsheet', 'Spreadsheet'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='media_files/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, help_text='Absolute URL populated on save')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
