# Generated by Django 4.2.7 on 2026-03-27 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0047_admission_settings_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Cash","MPesa","Bank Transfer"]'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='default_date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='language',
            field=models.CharField(default='en', help_text='BCP-47 language tag e.g. en, sw', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='late_fee_grace_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after due date before late fee applies'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='late_fee_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='late_fee_type',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PERCENT', 'Percent')], default='FLAT', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='late_fee_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', help_text='IANA timezone e.g. Africa/Nairobi', max_length=60),
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Dot-path key e.g. admission.format', max_length=100, unique=True)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(default='general', help_text='Grouping e.g. general, finance, academic, communication', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Setting',
                'verbose_name_plural': 'Tenant Settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
