# Generated by Django 4.2.7 on 2026-02-12 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0019_assignment_calendarevent_assignmentsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_alternate', models.CharField(blank=True, max_length=30)),
                ('email_personal', models.EmailField(blank=True, max_length=254)),
                ('email_work', models.EmailField(blank=True, max_length=254)),
                ('address_current', models.TextField(blank=True)),
                ('address_permanent', models.TextField(blank=True)),
                ('staff_type', models.CharField(choices=[('Teaching', 'Teaching'), ('Administrative', 'Administrative'), ('Support', 'Support'), ('Non-Teaching', 'Non-Teaching')], default='Teaching', max_length=20)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Visiting', 'Visiting')], default='Full-time', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Resigned', 'Resigned'), ('Retired', 'Retired')], default='Active', max_length=20)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_id', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('License', 'License')], default='Degree', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('institution', models.CharField(blank=True, max_length=180)),
                ('field_of_study', models.CharField(blank=True, max_length=180)),
                ('year_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='staff/qualifications/')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='staff_mgmt.staffmember')),
            ],
            options={
                'ordering': ['-year_obtained', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField()),
                ('lesson_topic', models.CharField(blank=True, max_length=180)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_improvement', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Acknowledged', 'Acknowledged')], default='Draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_observed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolclass')),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_given', to='staff_mgmt.staffmember')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='staff_mgmt.staffmember')),
            ],
            options={
                'ordering': ['-observation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('phone_primary', models.CharField(max_length=30)),
                ('phone_alt', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='staff_mgmt.staffmember')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Contract', 'Contract'), ('Certificate', 'Certificate'), ('License', 'License'), ('ID', 'ID'), ('Medical', 'Medical'), ('Performance', 'Performance'), ('Other', 'Other')], default='Other', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='staff/documents/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff_mgmt.staffmember')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_documents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('department_type', models.CharField(choices=[('Academic', 'Academic'), ('Administrative', 'Administrative'), ('Support', 'Support')], default='Academic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='staff_mgmt.staffmember')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='staff_mgmt.staffdepartment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff_mgmt.staffdepartment')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff_mgmt.staffrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff_mgmt.staffmember')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_period', models.CharField(max_length=60)),
                ('self_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('supervisor_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_development', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Acknowledged', 'Acknowledged')], default='Draft', max_length=20)),
                ('appraisal_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_given', to='staff_mgmt.staffmember')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='staff_mgmt.staffmember')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half-Day', 'Half-Day'), ('On Leave', 'On Leave')], default='Present', max_length=20)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff_mgmt.staffmember')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
