# Generated by Django 4.2.7 on 2026-02-12 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0002_leavetype_leaverequest_leavepolicy_leavebalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Processing", "Processing"),
                            ("Approved", "Approved"),
                            ("Paid", "Paid"),
                            ("Closed", "Closed"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("total_gross", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("total_deductions", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("total_net", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_payroll_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_payroll_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "-id"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("basic_salary", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "pay_frequency",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Bi-weekly", "Bi-weekly"), ("Weekly", "Weekly")],
                        default="Monthly",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "component_type",
                    models.CharField(
                        choices=[("Allowance", "Allowance"), ("Deduction", "Deduction")],
                        default="Allowance",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "amount_type",
                    models.CharField(
                        choices=[("Fixed", "Fixed"), ("Percentage", "Percentage")], default="Fixed", max_length=20
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_statutory", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="components", to="hr.salarystructure"
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("basic_salary", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("total_allowances", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("total_deductions", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("gross_salary", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("net_salary", models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ("days_worked", models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ("overtime_hours", models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="hr/payroll/payslips/")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payroll_items", to="hr.employee"
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="hr.payrollbatch"
                    ),
                ),
            ],
            options={
                "ordering": ["employee__employee_id", "id"],
                "unique_together": {("payroll", "employee")},
            },
        ),
    ]
