# Generated by Django 4.2.7 on 2026-02-12 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0003_salarystructure_salarycomponent_payrollbatch_payrollitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("Full-time", "Full-time"), ("Part-time", "Part-time"), ("Contract", "Contract")],
                        default="Full-time",
                        max_length=20,
                    ),
                ),
                ("salary_min", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("salary_max", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("Draft", "Draft"), ("Open", "Open"), ("Closed", "Closed")], default="Draft", max_length=20)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="job_postings", to="hr.department"),
                ),
                (
                    "position",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="job_postings", to="hr.position"),
                ),
                (
                    "posted_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hr_job_postings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task", models.CharField(max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("In Progress", "In Progress"), ("Completed", "Completed")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hr_onboarding_tasks", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "employee",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onboarding_tasks", to="hr.employee"),
                ),
            ],
            options={"ordering": ["status", "due_date", "id"]},
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("resume", models.FileField(blank=True, null=True, upload_to="hr/recruitment/resumes/")),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Screening", "Screening"),
                            ("Shortlisted", "Shortlisted"),
                            ("Interview", "Interview"),
                            ("Offer", "Offer"),
                            ("Rejected", "Rejected"),
                            ("Hired", "Hired"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "job_posting",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="hr.jobposting"),
                ),
            ],
            options={"ordering": ["-applied_at", "-id"]},
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interview_date", models.DateTimeField()),
                (
                    "interview_type",
                    models.CharField(choices=[("Phone", "Phone"), ("Video", "Video"), ("In-person", "In-person")], default="In-person", max_length=20),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("interviewers", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("Scheduled", "Scheduled"), ("Completed", "Completed"), ("Cancelled", "Cancelled"), ("No-show", "No-show")],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "application",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interviews", to="hr.jobapplication"),
                ),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hr_interviews", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-interview_date", "-id"]},
        ),
    ]
