# Generated by Django 4.2.7 on 2026-02-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_jobposting_jobapplication_interview_onboardingtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("Not Started", "Not Started"), ("In Progress", "In Progress"), ("Achieved", "Achieved"), ("Not Achieved", "Not Achieved")], default="Not Started", max_length=20)),
                ("weight", models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="performance_goals", to="hr.employee")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("trainer", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-start_date", "-id"]},
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("review_period", models.CharField(max_length=50)),
                ("overall_rating", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("strengths", models.TextField(blank=True)),
                ("areas_improvement", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("Draft", "Draft"), ("Submitted", "Submitted"), ("Acknowledged", "Acknowledged")], default="Draft", max_length=20)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="performance_reviews", to="hr.employee")),
                ("reviewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviews_given", to="hr.employee")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("Enrolled", "Enrolled"), ("Attended", "Attended"), ("Completed", "Completed"), ("Cancelled", "Cancelled")], default="Enrolled", max_length=20)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("certificate", models.FileField(blank=True, null=True, upload_to="hr/training/certificates/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="training_enrollments", to="hr.employee")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="hr.trainingprogram")),
            ],
            options={"ordering": ["-created_at", "-id"], "unique_together": {("program", "employee")}},
        ),
    ]
