# Generated by Django 4.2.7 on 2026-03-13 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0006_department_fk_to_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('Internal', 'Internal (Same School)'), ('External', 'External (Different School/County)')], default='Internal', max_length=20)),
                ('from_position', models.CharField(blank=True, max_length=150)),
                ('to_position', models.CharField(blank=True, max_length=150)),
                ('destination_school', models.CharField(blank=True, help_text='For External transfers', max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('handover_completed', models.BooleanField(default=False)),
                ('clearance_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hr.employee')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='hr.department')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='hr.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
