# Generated by Django 4.2.7 on 2026-03-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0031_store_dispensary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pickups', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('visitor_type', models.CharField(choices=[('Parent', 'Parent'), ('Contractor', 'Contractor'), ('Official', 'Official'), ('Other', 'Other')], default='Other', max_length=20)),
                ('purpose', models.TextField()),
                ('host_name', models.CharField(blank=True, help_text='Person/dept being visited', max_length=200)),
                ('badge_number', models.CharField(blank=True, max_length=20)),
                ('sign_in_time', models.DateTimeField(auto_now_add=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('In', 'Signed In'), ('Out', 'Signed Out')], default='In', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPickupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unauthorized_name', models.CharField(blank=True, help_text='If not in authorized list', max_length=200)),
                ('pickup_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('authorized', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('picked_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor_mgmt.authorizedpickup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
