# Generated by Django 4.2.7 on 2026-03-09 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0031_store_dispensary'),
        ('hr', '0005_performancegoal_performancereview_trainingprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('ENTRY', 'Entry Only'), ('EXIT', 'Exit Only'), ('BOTH', 'Entry & Exit')], max_length=10)),
                ('api_key', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('person_type', models.CharField(choices=[('ALL', 'All'), ('STUDENT', 'Students Only'), ('STAFF', 'Staff Only')], max_length=10)),
                ('expected_arrival', models.TimeField()),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('expected_departure', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.CharField(max_length=100, unique=True)),
                ('person_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teaching Staff'), ('STAFF', 'Non-Teaching Staff')], max_length=10)),
                ('display_name', models.CharField(max_length=200)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_late', models.BooleanField(default=False)),
                ('attendance_updated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clockin.biometricdevice')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clockin.personregistry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
