# Generated by Django 4.2.7 on 2026-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={'ordering': ['location', 'name']},
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='brand',
            field=models.CharField(default='Dahua', help_text='Device brand (Dahua / ZKTeco / Anviz / FingerTec / Suprema)', max_length=100),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='channel',
            field=models.PositiveIntegerField(default=1, help_text='Device channel number (Dahua default: 1)'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='discovery_method',
            field=models.CharField(blank=True, help_text='How the device was found (SADP / TCP / Manual)', max_length=100),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='http_port',
            field=models.PositiveIntegerField(default=80, help_text='HTTP web port (Dahua default: 80)'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Device IP address (Dahua factory default: 192.168.1.108)', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='model',
            field=models.CharField(blank=True, help_text='Device model (e.g. ASI6214S)', max_length=150),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='password',
            field=models.CharField(default='admin123', help_text='Device login password (Dahua default: admin123 or blank)', max_length=200),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='port',
            field=models.PositiveIntegerField(default=37777, help_text='SDK/main port (Dahua default: 37777)'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='rtsp_port',
            field=models.PositiveIntegerField(default=37778, help_text='RTSP stream port (Dahua default: 37778)'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='username',
            field=models.CharField(default='admin', help_text='Device login username (Dahua default: admin)', max_length=100),
        ),
    ]
