# Generated by Django 4.2.7 on 2026-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0002_add_device_connection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='personregistry',
            name='card_no',
            field=models.CharField(blank=True, db_index=True, help_text='RFID card number (Dahua CardNo field)', max_length=100),
        ),
        migrations.AddField(
            model_name='personregistry',
            name='dahua_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Dahua device UserID (EmployeeNoString). Leave blank to use fingerprint_id.', max_length=100),
        ),
        migrations.AlterField(
            model_name='personregistry',
            name='fingerprint_id',
            field=models.CharField(help_text='Primary biometric ID — also used as Dahua Employee No / UserID', max_length=100, unique=True),
        ),
    ]
