# Generated by Django 4.2.7 on 2026-03-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0004_add_smartpss_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartpsssource',
            name='device_model',
            field=models.CharField(blank=True, default='', help_text='Dahua device model managed by this SmartPSS instance, e.g. "AS16214S", "ASI7213X-T1", "ASI3214S"', max_length=100),
        ),
    ]
