# Generated by Django 4.2.7 on 2026-03-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0006_device_use_context_capture_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancecapturelog',
            new_name='clockin_att_timesta_7b8e76_idx',
            old_name='clockin_cap_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancecapturelog',
            new_name='clockin_att_device__a5b69f_idx',
            old_name='clockin_cap_dev_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancecapturelog',
            new_name='clockin_att_status_278877_idx',
            old_name='clockin_cap_status_idx',
        ),
    ]
