# Generated by Django 4.2.7 on 2026-03-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('school', '0031_store_dispensary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMealEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.mealplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_enrollments', to='school.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='CafeteriaWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('monday_breakfast', models.TextField(blank=True)),
                ('monday_lunch', models.TextField(blank=True)),
                ('monday_supper', models.TextField(blank=True)),
                ('tuesday_breakfast', models.TextField(blank=True)),
                ('tuesday_lunch', models.TextField(blank=True)),
                ('tuesday_supper', models.TextField(blank=True)),
                ('wednesday_breakfast', models.TextField(blank=True)),
                ('wednesday_lunch', models.TextField(blank=True)),
                ('wednesday_supper', models.TextField(blank=True)),
                ('thursday_breakfast', models.TextField(blank=True)),
                ('thursday_lunch', models.TextField(blank=True)),
                ('thursday_supper', models.TextField(blank=True)),
                ('friday_breakfast', models.TextField(blank=True)),
                ('friday_lunch', models.TextField(blank=True)),
                ('friday_supper', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menus', to='cafeteria.mealplan')),
            ],
            options={
                'unique_together': {('week_start', 'meal_plan')},
            },
        ),
        migrations.CreateModel(
            name='MealTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], default='Lunch', max_length=20)),
                ('served', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_transactions', to='school.student')),
            ],
            options={
                'unique_together': {('student', 'date', 'meal_type')},
            },
        ),
    ]
