# Generated by Django 4.2.7 on 2026-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='external_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
